#!/usr/bin/env python3
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
"""
Export stations.json metadata from backend to frontend.

Copies and validates the stations registry file from the backend config
directory to the frontend data directory for website consumption.

Source: ~/envcan_wave/config/stations.json
Output: ~/site/data/stations.json

This ensures the frontend always has the latest station metadata including
coordinates, names, types, and data sources for all buoys, tide stations,
and wind stations.
"""

import json
import shutil
from pathlib import Path

from lib.config import PROJECT_ROOT, EXPORT_DIR
from lib.logging_config import setup_logging

logger = setup_logging('stations_json_export')

# ---------- Config ----------
BACKEND_STATIONS = PROJECT_ROOT / "config" / "stations.json"
FRONTEND_STATIONS = EXPORT_DIR / "stations.json"


def validate_stations_json(file_path):
    """
    Validate that stations.json is valid JSON and has expected structure.

    Returns: (is_valid, error_message)
    """
    try:
        with open(file_path, 'r') as f:
            data = json.load(f)

        # Check for expected top-level keys
        required_keys = ['buoys', 'tides', 'wind']
        optional_keys = ['lightstations', 'webcams']

        missing_keys = [key for key in required_keys if key not in data]

        if missing_keys:
            return False, f"Missing required keys: {missing_keys}"

        # Check that each section is a dict
        all_keys = required_keys + [k for k in optional_keys if k in data]
        for key in all_keys:
            if not isinstance(data[key], dict):
                return False, f"Key '{key}' must be a dictionary, got {type(data[key])}"

        # Count stations
        counts = []
        counts.append(f"{len(data['buoys'])} buoys")
        counts.append(f"{len(data['tides'])} tides")
        counts.append(f"{len(data['wind'])} wind stations")

        if 'lightstations' in data:
            counts.append(f"{len(data['lightstations'])} lightstations")
        if 'webcams' in data:
            counts.append(f"{len(data['webcams'])} webcams")

        logger.info(f"Validated stations.json: {', '.join(counts)}")

        return True, None

    except json.JSONDecodeError as e:
        return False, f"Invalid JSON: {e}"
    except Exception as e:
        return False, f"Validation error: {e}"


def export_stations():
    """Export stations.json from backend to frontend with warning header."""
    try:
        # Check if backend file exists
        if not BACKEND_STATIONS.exists():
            logger.error(f"Backend stations.json not found: {BACKEND_STATIONS}")
            return False

        # Validate backend file before copying
        is_valid, error = validate_stations_json(BACKEND_STATIONS)
        if not is_valid:
            logger.error(f"Backend stations.json validation failed: {error}")
            return False

        # Load backend data
        with open(BACKEND_STATIONS, 'r') as f:
            data = json.load(f)

        # Add warning header (ordered dict to put it at the top)
        from collections import OrderedDict
        output = OrderedDict()
        output["_DO_NOT_EDIT"] = {
            "warning": "This file is AUTO-GENERATED by export_stations_json.py",
            "source": "~/envcan_wave/config/stations.json",
            "instructions": "To add/edit stations, edit the backend source file and re-run the export script",
            "last_generated": None  # Will be set below
        }

        # Add timestamp
        from datetime import datetime, timezone
        output["_DO_NOT_EDIT"]["last_generated"] = datetime.now(timezone.utc).isoformat()

        # Add all station data
        for key in data:
            output[key] = data[key]

        # Write to frontend with warning
        EXPORT_DIR.mkdir(parents=True, exist_ok=True)
        with open(FRONTEND_STATIONS, 'w') as f:
            json.dump(output, f, indent=2)

        logger.info(f"Exported stations.json: {BACKEND_STATIONS} → {FRONTEND_STATIONS}")

        # Verify frontend file (skip _DO_NOT_EDIT key in validation)
        is_valid, error = validate_stations_json(FRONTEND_STATIONS)
        if not is_valid:
            logger.error(f"Frontend stations.json validation failed after copy: {error}")
            return False

        return True

    except Exception as e:
        logger.error(f"Error exporting stations.json: {e}")
        return False


if __name__ == "__main__":
    success = export_stations()
    exit(0 if success else 1)
