broker amqps://dd.weather.gc.ca
topicPrefix v02.post

directory /home/keelando/envcan_wave/data/buoy
logDir /home/keelando/envcan_wave/logs

instances 1
batch 50
logLevel info

# Halibut Bank - 4600146
subtopic *.WXO-DD.observations.swob-ml.marine.moored-buoys.*.4600146.#

# Southern Strait of Georgia - 4600303
subtopic *.WXO-DD.observations.swob-ml.marine.moored-buoys.*.4600303.#

# English Bay - 4600304
subtopic *.WXO-DD.observations.swob-ml.marine.moored-buoys.*.4600304.#

# Sentry Shoal - 46131
subtopic *.WXO-DD.observations.swob-ml.marine.moored-buoys.*.4600131.#

# La Perouse Bank - 46206
subtopic *.WXO-DD.observations.swob-ml.marine.moored-buoys.*.4600206.#
